// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmWkTFJroh8X8ZF740KDu9uZZB8RPdh-o',
    appId: '1:957679485136:android:1ab4af43ef93344d98ded5',
    messagingSenderId: '957679485136',
    projectId: 'openlearning-smart-tv',
    storageBucket: 'openlearning-smart-tv.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyXEgzlGjy2DlOzgwo7V8ep7YamSvKOPg',
    appId: '1:957679485136:web:cd6e065923bb08a998ded5',
    messagingSenderId: '957679485136',
    projectId: 'openlearning-smart-tv',
    authDomain: 'openlearning-smart-tv.firebaseapp.com',
    storageBucket: 'openlearning-smart-tv.firebasestorage.app',
    measurementId: 'G-K8GK1FQEKZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMfcjBx1cOsCd4bQkr2QngbdczWVhw3bI',
    appId: '1:957679485136:ios:db023973c7cd0d4798ded5',
    messagingSenderId: '957679485136',
    projectId: 'openlearning-smart-tv',
    storageBucket: 'openlearning-smart-tv.firebasestorage.app',
    iosBundleId: 'com.example.smart',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMfcjBx1cOsCd4bQkr2QngbdczWVhw3bI',
    appId: '1:957679485136:ios:db023973c7cd0d4798ded5',
    messagingSenderId: '957679485136',
    projectId: 'openlearning-smart-tv',
    storageBucket: 'openlearning-smart-tv.firebasestorage.app',
    iosBundleId: 'com.example.smart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyXEgzlGjy2DlOzgwo7V8ep7YamSvKOPg',
    appId: '1:957679485136:web:bf06aae5227362e198ded5',
    messagingSenderId: '957679485136',
    projectId: 'openlearning-smart-tv',
    authDomain: 'openlearning-smart-tv.firebaseapp.com',
    storageBucket: 'openlearning-smart-tv.firebasestorage.app',
    measurementId: 'G-CE5SZHMZ6Z',
  );

}